// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "dovenet/user-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// CredentialRepository is an autogenerated mock type for the CredentialRepository type
type CredentialRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, credential
func (_m *CredentialRepository) Create(ctx context.Context, credential *domain.Credential) error {
	ret := _m.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Credential) error); ok {
		r0 = rf(ctx, credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: ctx, id
func (_m *CredentialRepository) DeleteByID(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CredentialRepository) GetByID(ctx context.Context, id int32) (*domain.Credential, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*domain.Credential, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *domain.Credential); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserTypeKey provides a mock function with given fields: ctx, userID, ctype, key
func (_m *CredentialRepository) GetByUserTypeKey(ctx context.Context, userID int32, ctype domain.CredentialType, key string) (*domain.Credential, error) {
	ret := _m.Called(ctx, userID, ctype, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserTypeKey")
	}

	var r0 *domain.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, domain.CredentialType, string) (*domain.Credential, error)); ok {
		return rf(ctx, userID, ctype, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, domain.CredentialType, string) *domain.Credential); ok {
		r0 = rf(ctx, userID, ctype, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, domain.CredentialType, string) error); ok {
		r1 = rf(ctx, userID, ctype, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, credential
func (_m *CredentialRepository) Update(ctx context.Context, credential *domain.Credential) error {
	ret := _m.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Credential) error); ok {
		r0 = rf(ctx, credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCredentialRepository creates a new instance of CredentialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCredentialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CredentialRepository {
	mock := &CredentialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
