// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "dovenet/user-service/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// OtpRepository is an autogenerated mock type for the OtpRepository type
type OtpRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, otp
func (_m *OtpRepository) Create(ctx context.Context, otp *domain.Otp) error {
	ret := _m.Called(ctx, otp)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Otp) error); ok {
		r0 = rf(ctx, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByID provides a mock function with given fields: ctx, id
func (_m *OtpRepository) DeleteByID(ctx context.Context, id int32) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *OtpRepository) GetByID(ctx context.Context, id int32) (*domain.Otp, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Otp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (*domain.Otp, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) *domain.Otp); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Otp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetValidOtp provides a mock function with given fields: ctx, userID, code, reason, medium
func (_m *OtpRepository) GetValidOtp(ctx context.Context, userID int32, code string, reason domain.OtpReason, medium domain.OtpMedium) (*domain.Otp, error) {
	ret := _m.Called(ctx, userID, code, reason, medium)

	if len(ret) == 0 {
		panic("no return value specified for GetValidOtp")
	}

	var r0 *domain.Otp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, domain.OtpReason, domain.OtpMedium) (*domain.Otp, error)); ok {
		return rf(ctx, userID, code, reason, medium)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32, string, domain.OtpReason, domain.OtpMedium) *domain.Otp); ok {
		r0 = rf(ctx, userID, code, reason, medium)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Otp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32, string, domain.OtpReason, domain.OtpMedium) error); ok {
		r1 = rf(ctx, userID, code, reason, medium)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, otp
func (_m *OtpRepository) Update(ctx context.Context, otp *domain.Otp) error {
	ret := _m.Called(ctx, otp)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Otp) error); ok {
		r0 = rf(ctx, otp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOtpRepository creates a new instance of OtpRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOtpRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OtpRepository {
	mock := &OtpRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
