// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"

	sql_repository "dovenet/user-service/internal/infrastructure/persistent/repository/sqlc"
)

// Querier is an autogenerated mock type for the Querier type
type Querier struct {
	mock.Mock
}

// CredentialCreate provides a mock function with given fields: ctx, arg
func (_m *Querier) CredentialCreate(ctx context.Context, arg sql_repository.CredentialCreateParams) (sql_repository.CredentialCreateRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CredentialCreate")
	}

	var r0 sql_repository.CredentialCreateRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.CredentialCreateParams) (sql_repository.CredentialCreateRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.CredentialCreateParams) sql_repository.CredentialCreateRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sql_repository.CredentialCreateRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql_repository.CredentialCreateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialDeleteByID provides a mock function with given fields: ctx, id
func (_m *Querier) CredentialDeleteByID(ctx context.Context, id int32) (int64, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CredentialDeleteByID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (int64, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) int64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialGetByID provides a mock function with given fields: ctx, id
func (_m *Querier) CredentialGetByID(ctx context.Context, id int32) (sql_repository.Credential, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CredentialGetByID")
	}

	var r0 sql_repository.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (sql_repository.Credential, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) sql_repository.Credential); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sql_repository.Credential)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialGetByUserTypeKey provides a mock function with given fields: ctx, arg
func (_m *Querier) CredentialGetByUserTypeKey(ctx context.Context, arg sql_repository.CredentialGetByUserTypeKeyParams) (sql_repository.Credential, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CredentialGetByUserTypeKey")
	}

	var r0 sql_repository.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.CredentialGetByUserTypeKeyParams) (sql_repository.Credential, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.CredentialGetByUserTypeKeyParams) sql_repository.Credential); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sql_repository.Credential)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql_repository.CredentialGetByUserTypeKeyParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CredentialUpdate provides a mock function with given fields: ctx, arg
func (_m *Querier) CredentialUpdate(ctx context.Context, arg sql_repository.CredentialUpdateParams) (sql.NullTime, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CredentialUpdate")
	}

	var r0 sql.NullTime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.CredentialUpdateParams) (sql.NullTime, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.CredentialUpdateParams) sql.NullTime); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sql.NullTime)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql_repository.CredentialUpdateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OtpCreate provides a mock function with given fields: ctx, arg
func (_m *Querier) OtpCreate(ctx context.Context, arg sql_repository.OtpCreateParams) (sql_repository.OtpCreateRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for OtpCreate")
	}

	var r0 sql_repository.OtpCreateRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.OtpCreateParams) (sql_repository.OtpCreateRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.OtpCreateParams) sql_repository.OtpCreateRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sql_repository.OtpCreateRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql_repository.OtpCreateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OtpDeleteByID provides a mock function with given fields: ctx, id
func (_m *Querier) OtpDeleteByID(ctx context.Context, id int32) (int64, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for OtpDeleteByID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (int64, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) int64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OtpGetByID provides a mock function with given fields: ctx, id
func (_m *Querier) OtpGetByID(ctx context.Context, id int32) (sql_repository.Otp, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for OtpGetByID")
	}

	var r0 sql_repository.Otp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (sql_repository.Otp, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) sql_repository.Otp); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sql_repository.Otp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OtpGetValidOtp provides a mock function with given fields: ctx, arg
func (_m *Querier) OtpGetValidOtp(ctx context.Context, arg sql_repository.OtpGetValidOtpParams) (sql_repository.Otp, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for OtpGetValidOtp")
	}

	var r0 sql_repository.Otp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.OtpGetValidOtpParams) (sql_repository.Otp, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.OtpGetValidOtpParams) sql_repository.Otp); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sql_repository.Otp)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql_repository.OtpGetValidOtpParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OtpUpdate provides a mock function with given fields: ctx, arg
func (_m *Querier) OtpUpdate(ctx context.Context, arg sql_repository.OtpUpdateParams) (sql.NullTime, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for OtpUpdate")
	}

	var r0 sql.NullTime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.OtpUpdateParams) (sql.NullTime, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.OtpUpdateParams) sql.NullTime); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sql.NullTime)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql_repository.OtpUpdateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserCreate provides a mock function with given fields: ctx, arg
func (_m *Querier) UserCreate(ctx context.Context, arg sql_repository.UserCreateParams) (sql_repository.UserCreateRow, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UserCreate")
	}

	var r0 sql_repository.UserCreateRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.UserCreateParams) (sql_repository.UserCreateRow, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.UserCreateParams) sql_repository.UserCreateRow); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sql_repository.UserCreateRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql_repository.UserCreateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserDeleteByEmail provides a mock function with given fields: ctx, email
func (_m *Querier) UserDeleteByEmail(ctx context.Context, email string) (int64, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UserDeleteByEmail")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserDeleteByID provides a mock function with given fields: ctx, id
func (_m *Querier) UserDeleteByID(ctx context.Context, id int32) (int64, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserDeleteByID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (int64, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) int64); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserDeleteByUsername provides a mock function with given fields: ctx, username
func (_m *Querier) UserDeleteByUsername(ctx context.Context, username string) (int64, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for UserDeleteByUsername")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserExistsByEmail provides a mock function with given fields: ctx, email
func (_m *Querier) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UserExistsByEmail")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserExistsByUsername provides a mock function with given fields: ctx, username
func (_m *Querier) UserExistsByUsername(ctx context.Context, username string) (bool, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for UserExistsByUsername")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetByEmail provides a mock function with given fields: ctx, email
func (_m *Querier) UserGetByEmail(ctx context.Context, email string) (sql_repository.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UserGetByEmail")
	}

	var r0 sql_repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sql_repository.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sql_repository.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(sql_repository.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetByID provides a mock function with given fields: ctx, id
func (_m *Querier) UserGetByID(ctx context.Context, id int32) (sql_repository.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UserGetByID")
	}

	var r0 sql_repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (sql_repository.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) sql_repository.User); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(sql_repository.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetByUsername provides a mock function with given fields: ctx, username
func (_m *Querier) UserGetByUsername(ctx context.Context, username string) (sql_repository.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for UserGetByUsername")
	}

	var r0 sql_repository.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (sql_repository.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) sql_repository.User); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(sql_repository.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserUpdate provides a mock function with given fields: ctx, arg
func (_m *Querier) UserUpdate(ctx context.Context, arg sql_repository.UserUpdateParams) (sql.NullTime, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UserUpdate")
	}

	var r0 sql.NullTime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.UserUpdateParams) (sql.NullTime, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, sql_repository.UserUpdateParams) sql.NullTime); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(sql.NullTime)
	}

	if rf, ok := ret.Get(1).(func(context.Context, sql_repository.UserUpdateParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQuerier creates a new instance of Querier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *Querier {
	mock := &Querier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
