// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credential.sql

package sql_repository

import (
	"context"
	"database/sql"
)

const credentialCreate = `-- name: CredentialCreate :one
insert into credentials (
    user_id, type, key, value
)
values
(
    $1, $2, $3, $4
)
returning id, created_at, updated_at
`

type CredentialCreateParams struct {
	UserID int32  `json:"user_id"`
	Type   string `json:"type"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

type CredentialCreateRow struct {
	ID        int32        `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) CredentialCreate(ctx context.Context, arg CredentialCreateParams) (CredentialCreateRow, error) {
	row := q.db.QueryRowContext(ctx, credentialCreate,
		arg.UserID,
		arg.Type,
		arg.Key,
		arg.Value,
	)
	var i CredentialCreateRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const credentialDeleteByID = `-- name: CredentialDeleteByID :execrows
update credentials set
    deleted_at = now()
where id = $1 and deleted_at is null
`

func (q *Queries) CredentialDeleteByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, credentialDeleteByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const credentialGetByID = `-- name: CredentialGetByID :one

select id, created_at, updated_at, deleted_at, user_id, type, key, value from credentials
    where id = $1 and deleted_at is null
limit 1
`

// sql/queries/credential.sql
func (q *Queries) CredentialGetByID(ctx context.Context, id int32) (Credential, error) {
	row := q.db.QueryRowContext(ctx, credentialGetByID, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.Type,
		&i.Key,
		&i.Value,
	)
	return i, err
}

const credentialGetByUserTypeKey = `-- name: CredentialGetByUserTypeKey :one
select id, created_at, updated_at, deleted_at, user_id, type, key, value from credentials
    where user_id = $1 and type = $2 and key = $3 and deleted_at is null
limit 1
`

type CredentialGetByUserTypeKeyParams struct {
	UserID int32  `json:"user_id"`
	Type   string `json:"type"`
	Key    string `json:"key"`
}

func (q *Queries) CredentialGetByUserTypeKey(ctx context.Context, arg CredentialGetByUserTypeKeyParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, credentialGetByUserTypeKey, arg.UserID, arg.Type, arg.Key)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.Type,
		&i.Key,
		&i.Value,
	)
	return i, err
}

const credentialUpdate = `-- name: CredentialUpdate :one
update credentials set
    user_id = $2,
    type = $3,
    key = $4,
    value = $5
where id = $1 and deleted_at is null
returning updated_at
`

type CredentialUpdateParams struct {
	ID     int32  `json:"id"`
	UserID int32  `json:"user_id"`
	Type   string `json:"type"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}

func (q *Queries) CredentialUpdate(ctx context.Context, arg CredentialUpdateParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, credentialUpdate,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Key,
		arg.Value,
	)
	var updated_at sql.NullTime
	err := row.Scan(&updated_at)
	return updated_at, err
}
