// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql_repository

import (
	"database/sql"
)

type Credential struct {
	ID        int32        `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UserID    int32        `json:"user_id"`
	Type      string       `json:"type"`
	Key       string       `json:"key"`
	Value     string       `json:"value"`
}

type Otp struct {
	ID        int32        `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	UserID    int32        `json:"user_id"`
	Reason    string       `json:"reason"`
	Medium    string       `json:"medium"`
	Code      string       `json:"code"`
	UsedAt    sql.NullTime `json:"used_at"`
}

type User struct {
	ID          int32          `json:"id"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	Email       string         `json:"email"`
	Username    string         `json:"username"`
	Firstname   sql.NullString `json:"firstname"`
	Lastname    sql.NullString `json:"lastname"`
	IsSuperuser sql.NullBool   `json:"is_superuser"`
	IsVerified  sql.NullBool   `json:"is_verified"`
}
