// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp.sql

package sql_repository

import (
	"context"
	"database/sql"
)

const otpCreate = `-- name: OtpCreate :one
insert into otps (
    user_id,
    code,
    reason,
    medium,
    used_at
) values ($1, $2, $3, $4, $5)
returning id, created_at, updated_at
`

type OtpCreateParams struct {
	UserID int32        `json:"user_id"`
	Code   string       `json:"code"`
	Reason string       `json:"reason"`
	Medium string       `json:"medium"`
	UsedAt sql.NullTime `json:"used_at"`
}

type OtpCreateRow struct {
	ID        int32        `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) OtpCreate(ctx context.Context, arg OtpCreateParams) (OtpCreateRow, error) {
	row := q.db.QueryRowContext(ctx, otpCreate,
		arg.UserID,
		arg.Code,
		arg.Reason,
		arg.Medium,
		arg.UsedAt,
	)
	var i OtpCreateRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const otpDeleteByID = `-- name: OtpDeleteByID :execrows
update otps set
    deleted_at = now()
where id = $1 and deleted_at is null
`

func (q *Queries) OtpDeleteByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, otpDeleteByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const otpGetByID = `-- name: OtpGetByID :one

select id, created_at, updated_at, deleted_at, user_id, reason, medium, code, used_at from otps
    where id = $1 and deleted_at is null
limit 1
`

// sql/queries/otp.sql
func (q *Queries) OtpGetByID(ctx context.Context, id int32) (Otp, error) {
	row := q.db.QueryRowContext(ctx, otpGetByID, id)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.Reason,
		&i.Medium,
		&i.Code,
		&i.UsedAt,
	)
	return i, err
}

const otpGetValidOtp = `-- name: OtpGetValidOtp :one
select id, created_at, updated_at, deleted_at, user_id, reason, medium, code, used_at from otps
where 
    user_id = $1 and code = $2 and 
    reason = $3 and medium = $4 and used_at is null and deleted_at is null
limit 1
`

type OtpGetValidOtpParams struct {
	UserID int32  `json:"user_id"`
	Code   string `json:"code"`
	Reason string `json:"reason"`
	Medium string `json:"medium"`
}

func (q *Queries) OtpGetValidOtp(ctx context.Context, arg OtpGetValidOtpParams) (Otp, error) {
	row := q.db.QueryRowContext(ctx, otpGetValidOtp,
		arg.UserID,
		arg.Code,
		arg.Reason,
		arg.Medium,
	)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID,
		&i.Reason,
		&i.Medium,
		&i.Code,
		&i.UsedAt,
	)
	return i, err
}

const otpUpdate = `-- name: OtpUpdate :one
update otps set
    user_id = $2,
    code = $3,
    reason = $4,
    medium = $5,
    used_at = $6
where id = $1 and deleted_at is null
returning updated_at
`

type OtpUpdateParams struct {
	ID     int32        `json:"id"`
	UserID int32        `json:"user_id"`
	Code   string       `json:"code"`
	Reason string       `json:"reason"`
	Medium string       `json:"medium"`
	UsedAt sql.NullTime `json:"used_at"`
}

func (q *Queries) OtpUpdate(ctx context.Context, arg OtpUpdateParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, otpUpdate,
		arg.ID,
		arg.UserID,
		arg.Code,
		arg.Reason,
		arg.Medium,
		arg.UsedAt,
	)
	var updated_at sql.NullTime
	err := row.Scan(&updated_at)
	return updated_at, err
}
