// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sql_repository

import (
	"context"
	"database/sql"
)

type Querier interface {
	CredentialCreate(ctx context.Context, arg CredentialCreateParams) (CredentialCreateRow, error)
	CredentialDeleteByID(ctx context.Context, id int32) (int64, error)
	// sql/queries/credential.sql
	CredentialGetByID(ctx context.Context, id int32) (Credential, error)
	CredentialGetByUserTypeKey(ctx context.Context, arg CredentialGetByUserTypeKeyParams) (Credential, error)
	CredentialUpdate(ctx context.Context, arg CredentialUpdateParams) (sql.NullTime, error)
	OtpCreate(ctx context.Context, arg OtpCreateParams) (OtpCreateRow, error)
	OtpDeleteByID(ctx context.Context, id int32) (int64, error)
	// sql/queries/otp.sql
	OtpGetByID(ctx context.Context, id int32) (Otp, error)
	OtpGetValidOtp(ctx context.Context, arg OtpGetValidOtpParams) (Otp, error)
	OtpUpdate(ctx context.Context, arg OtpUpdateParams) (sql.NullTime, error)
	UserCreate(ctx context.Context, arg UserCreateParams) (UserCreateRow, error)
	UserDeleteByEmail(ctx context.Context, email string) (int64, error)
	UserDeleteByID(ctx context.Context, id int32) (int64, error)
	UserDeleteByUsername(ctx context.Context, username string) (int64, error)
	UserExistsByEmail(ctx context.Context, email string) (bool, error)
	UserExistsByUsername(ctx context.Context, username string) (bool, error)
	UserGetByEmail(ctx context.Context, email string) (User, error)
	// sql/queries/users.sql
	UserGetByID(ctx context.Context, id int32) (User, error)
	UserGetByUsername(ctx context.Context, username string) (User, error)
	UserUpdate(ctx context.Context, arg UserUpdateParams) (sql.NullTime, error)
}

var _ Querier = (*Queries)(nil)
