// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sql_repository

import (
	"context"
	"database/sql"
)

const userCreate = `-- name: UserCreate :one
insert into users (
    email, username, firstname,
    lastname, is_superuser, is_verified
) values 
($1, $2, $3, $4, $5, $6)
returning id, created_at, updated_at
`

type UserCreateParams struct {
	Email       string         `json:"email"`
	Username    string         `json:"username"`
	Firstname   sql.NullString `json:"firstname"`
	Lastname    sql.NullString `json:"lastname"`
	IsSuperuser sql.NullBool   `json:"is_superuser"`
	IsVerified  sql.NullBool   `json:"is_verified"`
}

type UserCreateRow struct {
	ID        int32        `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) (UserCreateRow, error) {
	row := q.db.QueryRowContext(ctx, userCreate,
		arg.Email,
		arg.Username,
		arg.Firstname,
		arg.Lastname,
		arg.IsSuperuser,
		arg.IsVerified,
	)
	var i UserCreateRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const userDeleteByEmail = `-- name: UserDeleteByEmail :execrows
update users set
    deleted_at = now()
where email = $1 and deleted_at is null
`

func (q *Queries) UserDeleteByEmail(ctx context.Context, email string) (int64, error) {
	result, err := q.db.ExecContext(ctx, userDeleteByEmail, email)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const userDeleteByID = `-- name: UserDeleteByID :execrows
update users set
    deleted_at = now()
where id = $1 and deleted_at is null
`

func (q *Queries) UserDeleteByID(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.ExecContext(ctx, userDeleteByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const userDeleteByUsername = `-- name: UserDeleteByUsername :execrows
update users set
    deleted_at = now()
where username = $1 and deleted_at is null
`

func (q *Queries) UserDeleteByUsername(ctx context.Context, username string) (int64, error) {
	result, err := q.db.ExecContext(ctx, userDeleteByUsername, username)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const userExistsByEmail = `-- name: UserExistsByEmail :one
select exists (
    select 1 from users
    where email = $1 and deleted_at is null
) as exists
`

func (q *Queries) UserExistsByEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExistsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userExistsByUsername = `-- name: UserExistsByUsername :one
select exists (
    select 1 from users
    where username = $1 and deleted_at is null
) as exists
`

func (q *Queries) UserExistsByUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userExistsByUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userGetByEmail = `-- name: UserGetByEmail :one
SELECT id, created_at, updated_at, deleted_at, email, username, firstname, lastname, is_superuser, is_verified from users
    where email = $1 and deleted_at is null
limit 1
`

func (q *Queries) UserGetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, userGetByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.IsSuperuser,
		&i.IsVerified,
	)
	return i, err
}

const userGetByID = `-- name: UserGetByID :one

SELECT id, created_at, updated_at, deleted_at, email, username, firstname, lastname, is_superuser, is_verified from users
    where id = $1 and deleted_at is null
limit 1
`

// sql/queries/users.sql
func (q *Queries) UserGetByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRowContext(ctx, userGetByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.IsSuperuser,
		&i.IsVerified,
	)
	return i, err
}

const userGetByUsername = `-- name: UserGetByUsername :one
SELECT id, created_at, updated_at, deleted_at, email, username, firstname, lastname, is_superuser, is_verified from users
    where username = $1 and deleted_at is null
limit 1
`

func (q *Queries) UserGetByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, userGetByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Email,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.IsSuperuser,
		&i.IsVerified,
	)
	return i, err
}

const userUpdate = `-- name: UserUpdate :one
update users set
    updated_at = default,
    email = $2,
    username = $3,
    firstname = $4,
    lastname = $5,
    is_superuser = $6,
    is_verified = $7
where id = $1 and deleted_at is null
returning updated_at
`

type UserUpdateParams struct {
	ID          int32          `json:"id"`
	Email       string         `json:"email"`
	Username    string         `json:"username"`
	Firstname   sql.NullString `json:"firstname"`
	Lastname    sql.NullString `json:"lastname"`
	IsSuperuser sql.NullBool   `json:"is_superuser"`
	IsVerified  sql.NullBool   `json:"is_verified"`
}

func (q *Queries) UserUpdate(ctx context.Context, arg UserUpdateParams) (sql.NullTime, error) {
	row := q.db.QueryRowContext(ctx, userUpdate,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Firstname,
		arg.Lastname,
		arg.IsSuperuser,
		arg.IsVerified,
	)
	var updated_at sql.NullTime
	err := row.Scan(&updated_at)
	return updated_at, err
}
